#Makefile for the edison cluster
SRCDIR?=.
include $(SRCDIR)/Makefile.arch
# Directory for math routines
ROUT = $(SRCDIR)/mathlib
# Directory for math routines
CUB = $(SRCDIR)/cubpack
#
COREDIR=$(SRCDIR)/core
MAKEFLUXDIR=$(COREDIR)/make_flux
# Fortran files for QUALIKIZ

OBJS_MAKEFLUX = kind.o mod_io_management.o datmat.o datcal.o asymmetry.o mod_saturation.o
OBJS_QUALIKIZ = mod_fonct.o callpassQLints.o calltrapQLints.o QLflux.o nanfilter.o calcroutines.o mod_saturation.o qualikiz.o
#OBJS_QUALIKIZ_AUX = dispfuncs.o mod_make_io.o \
FLRterms.o mod_fluidsol.o mod_contour.o trapints.o passints.o calltrapints.o callpassints.o \


# Parallel or serial compilation
ifneq ($(MPI_FLAGS),-DMPI)
      OBJS_QUALIKIZ += mpivoid.o
endif

FFLAGS_QUALIKIZ= -ffree-line-length-none -fintrinsic-modules-path $(COREDIR) -fintrinsic-modules-path $(CUB)
all: $(OBJS_QUALIKIZ) $(CUB)/libcubpack.a $(ROUT)/librout.a 
#all: $(CUB)/libcubpack.a $(ROUT)/librout.a QuaLiKiz.exe
# qlk_makeflux.exe qlk_redoQL.exe

#qlk_redoQL.exe: qlk_redoQL.f90 $(OBJS_MAKEFLUX) $(ROUT)/librout.a
#	$(FC) -o qlk_redoQL.exe qlk_redoQL.f90 $(OBJS_QUALIKIZ) ${QFLAGS} ${OPENMP} $(MPI) -L$(ROUT) -lrout -L$(CUB) -lcubpack 

#qlk_makeflux.exe: qlk_makeflux.f90 $(OBJS_MAKEFLUX) $(ROUT)/librout.a
#	$(FC) -o qlk_makeflux.exe qlk_makeflux.f90 $(OBJS_QUALIKIZ) ${QFLAGS} ${OPENMP} $(MPI) -L$(ROUT) -lrout -L$(CUB) -lcubpack 

# dependencies
#include $(COREDIR)/Makefile
include $(COREDIR)/Makefile
include $(ROUT)/Makefile
include $(CUB)/Makefile
SRCS_QUALIKIZ=qlflux.f90 callpassqlints.f90 calltrapqlints.f90 nanfilter.f90  qualikiz.f90
OBJS_QUALIKIZ=$(SRCS_QUALIKIZ:%f90=%o)
MODS_QUALIKIZ=$(SRCS_QUALIKIZ:%.f90=%.mod) mod_fonct.mod calcroutines.mod qlk_standalone.mod

qualikiz.o: qualikiz.f90 mod_make_io.mod calcroutines.mod mod_saturation.mod
calcroutines.o: calcroutines.f90 kind.mod datcal.mod datmat.mod FLRterms.mod mod_fluidsol.mod mod_contour.mod mod_make_io.mod mod_fonct.mod qlflux.mod asymmetry.mod nanfilter.mod
	$(FC) -static -fdefault-real-8 $(FFLAGS_QUALIKIZ) -c ${QFLAGS} $(MPI) $(OPENMP) $< -J $(@D) -o $@
#datcal.mod datmat.mod FLRterms.mod mod_fluidsol.mod mod_contour.mod mod_make_io.mod mod_io_management.mod
mod_fonct.o: mod_fonct.f90 callpassints.mod cui.mod calltrapints.mod
	$(FC) -fdefault-real-8 $(FFLAGS_QUALIKIZ) -c ${QFLAGS} $(MPI) $(OPENMP) $< -J $(@D) -o $@


QuaLiKiz.exe: qlk_standalone.f90 qualikiz.f90 $(OBJS_QUALIKIZ) $(ROUT)/librout.a $(CUB)/libcubpack.a mod_io_management.mod qualikiz.mod datmat.mod
	$(FC) -fdefault-real-8 $(FFLAGS_QUALIKIZ) qlk_standalone.f90 $(OBJS_QUALIKIZ) core/datmat.o core/mod_make_io.o  ${QFLAGS} ${OPENMP} $(MPI) -L$(COREDIR) -L$(ROUT) mod_fonct.o calcroutines.o core/calltrapints.o core/callpassints.o core/mod_io_management.o core/passints.o core/trapints.o core/asymmetry.o core/dispfuncs.o core/mod_saturation.o core/datcal.o core/FLRterms.o core/mod_contour.o core/mod_fluidsol.o -lrout -L$(CUB) -lcubpack -o QuaLiKiz.exe -fopenmp


$(OBJS_QUALIKIZ):%.o:$(SRCDIR)/%.f90
	$(FC) $(FFLAGS_QUALIKIZ) -c ${QFLAGS} $(MPI) $(OPENMP) $< -J $(SRCDIR)/$(*D) -o $(SRCDIR)/$*.o

callpassqlints.o: callpassqlints.f90 callpassints.mod cui.mod
	$(FC) -fdefault-real-8 $(FFLAGS_QUALIKIZ) -c ${QFLAGS} $(MPI) $(OPENMP) $< -J $(@D) -o $@

calltrapqlints.o: calltrapqlints.f90 calltrapints.mod cui.mod
	$(FC) -fdefault-real-8 $(FFLAGS_QUALIKIZ) -c ${QFLAGS} $(MPI) $(OPENMP) $< -J $(@D) -o $@
$(MODS_QUALIKIZ):%.mod:%.o
	
qlflux.o: qlflux.f90 kind.mod datmat.mod datcal.mod callpassqlints.mod calltrapqlints.mod
	$(FC) -fdefault-real-8 $(FFLAGS_QUALIKIZ) -c ${QFLAGS} $(MPI) $(OPENMP) $< -J $(@D) -o $@

qlk_standalone.o: qlk_standalone.f90 kind.mod mod_io_management.mod
	$(FC) -fdefault-real-8 $(FFLAGS_QUALIKIZ) -c ${QFLAGS} $(MPI) $(OPENMP) $< -J $(SRCDIR)/$(@D) -o $@

nanfilter.o: nanfilter.f90
	$(FC) -fdefault-real-8 $(FFLAGS_QUALIKIZ) -c ${QFLAGS} $(MPI) $(OPENMP) $< -J $(SRCDIR)/$(@D) -o $@
#%.o:%.f90
#	@echo MainMakefile
#	@echo $(COREDEPS)
#	$(FC) $(FFLAGS_QUALIKIZ) -c ${QFLAGS} $(MPI) $(OPENMP) $< -J $(@D) -o $@
#
##mod_fonct.o: $(MAKEFLUXDIR)/datcal.mod $(MAKEFLUXDIR)/datmat.mod
#%.mod:%.o
	
$(ROUT)/librout.a:
	make -C $(ROUT) librout.a

$(CUB)/libcubpack.a:
	make -C $(CUB) libcubpack.a

## Child dependencies
#$(MAKEFLUXDIR)/kind.mod $(MAKEFLUXDIR)/mod_io_management.mod $(MAKEFLUXDIR)/datcal.mod $(MAKEFLUXDIR)/datmat.mod:
#	make -C $(MAKEFLUXDIR) $(@F)
clean:
	make -C $(CUB) clean
	make -C $(ROUT) clean
	make -C $(COREDIR) clean
	rm -f *.o *.exe *.mod

distclean:
	make -C $(CUB) distclean
	make -C $(ROUT) distclean
	make -C $(COREDIR) distclean
	rm -f *.o *.exe *.mod

dump_variables:
	@echo ARCH=$(ARCH)
	@echo FC_TYPE=$(FC_TYPE)
	@echo INCLUDE_MPI=$(INCLUDE_MPI)
	@echo OPENMP=$(OPENMP)
	@echo LIB_MPI=$(LIB_MPI)
	@echo FC=$(FC)
	@echo FFLAGS=$(FFLAGS)
	@echo FLIBS=$(FLIBFS)
	@echo QFLAGS=$(QFLAGS)
