#!/bin/make -f
QLKDIR+
# Underlying compiler
FC=ifort
# Wrapper/command used to compile with Open MPI
FC_WRAPPER=mpif90
# String of text that will be put in from of the $(FC) compile option
FC_PREAMBLE=export OMPI_FC=$(FC) && 
DEBUG=
FFLAGS_GFORTRAN=$(DEBUG) -O3 -fdefault-double-8 -fdefault-real-8 -ffree-line-length-none
FFLAGS_IFORT=$(DEBUG) -O2 -real-size 64
FFLAGS=$(FFLAGS_IFORT)
OPENMP_FLAGS=-openmp
MPI_FLAGS=-DMPI
